{% set version = "6.0.0" %}

package:
  name: pillow
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/P/Pillow/Pillow-{{ version }}.tar.gz
  sha256: 809c0a2ce9032cbcd7b5313f71af4bdc5c8c771cb86eb7559afd954cab82ebb5

build:
  number: 1

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
    - zlib
    - libtiff
    - libwebp
    - jpeg
    - freetype
    - tk
  run:
    - python
    - jpeg
    - zlib
    - freetype
    - libtiff
    - libwebp
    - olefile
    - tk

test:
  imports:
    - PIL
    - PIL.Image

about:
  home: https://pillow.readthedocs.io
  license: PIL
  license_file: LICENSE
  summary: 'Pillow is the friendly PIL fork by Alex Clark and Contributors'

extra:
  recipe-maintainers:
    - jakirkham
    - patricksnape
    - pelson
    - ocefpaf
